tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      maxWidth: {
        "7xl": "1536px",
        "8xl": "1680px",
      },
      colors: {
        "on-tertiary": "#ffffff",
        secondary: "#745b19",
        "on-primary-fixed-variant": "#3b4662",
        "tertiary-container": "#002e41",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#9acded",
        "on-primary-fixed": "#0f1b34",
        "error-container": "#ffdad6",
        "inverse-primary": "#bbc6e7",
        primary: "#09152e",
        background: "#f6f9ff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#6598b6",
        "on-error": "#ffffff",
        "on-background": "#0e1d28",
        "on-surface": "#0e1d28",
        "outline-variant": "#c6c6ce",
        "on-tertiary-fixed": "#001e2c",
        "inverse-surface": "#23323e",
        surface: "#f6f9ff",
        "surface-container-high": "#daeafa",
        "secondary-fixed": "#ffdf98",
        "on-primary-container": "#8691b0",
        "surface-tint": "#535e7b",
        "on-secondary-fixed": "#251a00",
        "surface-container-low": "#ebf5ff",
        "on-surface-variant": "#45464d",
        "primary-container": "#1f2a44",
        "primary-fixed": "#d9e2ff",
        "inverse-on-surface": "#e6f2ff",
        "primary-fixed-dim": "#bbc6e7",
        "surface-container-highest": "#d5e4f4",
        "surface-variant": "#d5e4f4",
        "on-secondary-fixed-variant": "#5a4301",
        "surface-dim": "#ccdceb",
        "on-error-container": "#93000a",
        tertiary: "#001825",
        "tertiary-fixed": "#c4e7ff",
        outline: "#76777e",
        "secondary-container": "#fedc8d",
        "secondary-fixed-dim": "#e4c377",
        "on-secondary-container": "#785f1d",
        "on-tertiary-fixed-variant": "#0d4c67",
        "surface-bright": "#f6f9ff",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        "space-lg": "1.75rem",
        "margin-mobile": "1.25rem",
        "space-xl": "3rem",
        "space-xs": "0.25rem",
        margin: "4rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        caption: ["DM Sans"],
        "headline-md": ["Noto Serif"],
        "display-lg": ["Noto Serif"],
        "editorial-quote": ["Noto Serif"],
        "label-md": ["DM Sans"],
        "headline-lg": ["Noto Serif"],
        "display-sm-mobile": ["Noto Serif"],
        "body-lg": ["DM Sans"],
        "display-sm": ["Noto Serif"],
        "body-sm": ["DM Sans"],
        "headline-sm": ["Noto Serif"],
        "label-lg": ["DM Sans"],
        "body-md": ["DM Sans"],
        "display-lg-mobile": ["Noto Serif"],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": [
          "56px",
          {
            lineHeight: "64px",
            letterSpacing: "-0.02em",
            fontWeight: "400",
          },
        ],
        "editorial-quote": ["22px", { lineHeight: "34px", fontWeight: "400" }],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.06em",
            fontWeight: "600",
          },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-sm-mobile": [
          "30px",
          { lineHeight: "38px", fontWeight: "400" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-sm": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.01em",
            fontWeight: "400",
          },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": [
          "14px",
          {
            lineHeight: "18px",
            letterSpacing: "0.08em",
            fontWeight: "600",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": [
          "38px",
          {
            lineHeight: "46px",
            letterSpacing: "-0.01em",
            fontWeight: "400",
          },
        ],
      },
    },
  },
};
