tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      maxWidth: {
        "7xl": "1536px",
        "8xl": "1680px",
      },
      colors: {
        "on-tertiary": "#ffffff",
        secondary: "#856209",
        "on-primary-fixed-variant": "#2a4868",
        "tertiary-container": "#031d34",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#02203c",
        "tertiary-fixed-dim": "#8ebbe6",
        "on-primary-fixed": "#02203c",
        "error-container": "#ffdad6",
        "inverse-primary": "#a6cdfc",
        primary: "#02203c",
        background: "#f4f8fc",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#6b9ac4",
        "on-error": "#ffffff",
        "on-background": "#02203c",
        "on-surface": "#02203c",
        "outline-variant": "#c2d1e0",
        "on-tertiary-fixed": "#011324",
        "inverse-surface": "#12283e",
        surface: "#f4f8fc",
        "surface-container-high": "#d6e5f5",
        "secondary-fixed": "#fbcb62",
        "on-primary-container": "#93b4d6",
        "surface-tint": "#02203c",
        "on-secondary-fixed": "#02203c",
        "surface-container-low": "#eaf2fa",
        "on-surface-variant": "#405469",
        "primary-container": "#06294a",
        "primary-fixed": "#cfe3fb",
        "inverse-on-surface": "#ebf3fa",
        "primary-fixed-dim": "#a6cdfc",
        "surface-container-highest": "#cce0f2",
        "surface-variant": "#d6e5f5",
        "on-secondary-fixed-variant": "#463402",
        "surface-dim": "#c2d6e9",
        "on-error-container": "#93000a",
        tertiary: "#011628",
        "tertiary-fixed": "#bee0ff",
        outline: "#698199",
        "secondary-container": "#fde4a0",
        "secondary-fixed-dim": "#e9b84b",
        "on-secondary-container": "#463402",
        "on-tertiary-fixed-variant": "#0d395e",
        "surface-bright": "#f4f8fc",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        "space-lg": "1.75rem",
        "margin-mobile": "1.25rem",
        "space-xl": "3rem",
        "space-xs": "0.25rem",
        margin: "4rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        caption: ["DM Sans"],
        "headline-md": ["Noto Serif"],
        "display-lg": ["Noto Serif"],
        "editorial-quote": ["Noto Serif"],
        "label-md": ["DM Sans"],
        "headline-lg": ["Noto Serif"],
        "display-sm-mobile": ["Noto Serif"],
        "body-lg": ["DM Sans"],
        "display-sm": ["Noto Serif"],
        "body-sm": ["DM Sans"],
        "headline-sm": ["Noto Serif"],
        "label-lg": ["DM Sans"],
        "body-md": ["DM Sans"],
        "display-lg-mobile": ["Noto Serif"],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": [
          "56px",
          {
            lineHeight: "64px",
            letterSpacing: "-0.02em",
            fontWeight: "400",
          },
        ],
        "editorial-quote": ["22px", { lineHeight: "34px", fontWeight: "400" }],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.06em",
            fontWeight: "600",
          },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-sm-mobile": [
          "30px",
          { lineHeight: "38px", fontWeight: "400" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-sm": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.01em",
            fontWeight: "400",
          },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": [
          "14px",
          {
            lineHeight: "18px",
            letterSpacing: "0.08em",
            fontWeight: "600",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": [
          "38px",
          {
            lineHeight: "46px",
            letterSpacing: "-0.01em",
            fontWeight: "400",
          },
        ],
      },
    },
  },
};
